/**
 * Band `010_` (CORE-004) — projects, series, episodes (spec §23, §25).
 *
 * Hierarchy: a project is the top-level container (standalone movie or the
 * root of a series). A series belongs to exactly one project. An episode
 * belongs to exactly one series and one season. `project_id` is denormalized
 * onto episodes for fast "all episodes of a project" listing; the composite
 * unique key keeps the (series, season, episode) position unique, which is
 * what the deterministic code (e.g. `S01E03`) and GHL folder tree (spec §19)
 * rely on — two series inside one project may each have an `S01E01`.
 *
 * Aspect ratio (spec §23): the master format is captured once at series
 * creation (`series.aspect_ratio`), with a nullable per-episode override
 * (`episodes.aspect_ratio_override`). `NULL` = inherit from the series.
 * Custom ratios are free-form strings ("16:9", "9:16", "2.39:1") validated
 * by the repositories, not a CHECK constraint, so new formats need no
 * migration.
 *
 * Every table uses a TEXT primary key (mmcs_* ULID-style ids generated by
 * the repositories) and `STRICT` typing, matching the baseline band's
 * conventions.
 */
export const projectSchemaMigrations: readonly ProjectSchemaMigration[] = [
  {
    id: "0101",
    name: "create projects table",
    up: `
CREATE TABLE projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'series' CHECK (kind IN ('series', 'standalone')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  aspect_ratio TEXT NOT NULL DEFAULT '16:9',
  ghl_folder_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
) STRICT;
`.trim(),
    down: "DROP TABLE IF EXISTS projects;",
  },
  {
    id: "0102",
    name: "create series table",
    up: `
CREATE TABLE series (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  aspect_ratio TEXT NOT NULL DEFAULT '16:9',
  ghl_folder_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (project_id, name)
) STRICT;
CREATE INDEX idx_series_project ON series(project_id);
`.trim(),
    down: "DROP TABLE IF EXISTS series;",
  },
  {
    id: "0103",
    name: "create episodes table",
    up: `
CREATE TABLE episodes (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  series_id TEXT NOT NULL REFERENCES series(id) ON DELETE CASCADE,
  season_number INTEGER NOT NULL,
  episode_number INTEGER NOT NULL,
  code TEXT NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'scripted', 'storyboarded', 'generated', 'rough_cut', 'final', 'archived')),
  aspect_ratio_override TEXT,
  target_runtime_seconds INTEGER,
  ghl_folder_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (series_id, season_number, episode_number)
) STRICT;
CREATE INDEX idx_episodes_series ON episodes(series_id);
CREATE INDEX idx_episodes_project ON episodes(project_id);
`.trim(),
    down: "DROP TABLE IF EXISTS episodes;",
  },
];

export interface ProjectSchemaMigration {
  readonly id: string;
  readonly name: string;
  readonly up: string;
  readonly down: string;
}