// Final render contract (VID-014) — spec §21 (final render step of the
// Remotion pipeline), §3 gate 5, §23 output formats, §17 `08 Final/` layout.
//
// VID-014 owns packages/remotion-runtime/src/final-render/. Upstream tasks it
// consumes are NOT merged yet (VID-012 rough-cut, VID-015 ffprobe, CORE-008
// approval gates), so every collaborator arrives as an injected structural
// port — the same dependency-injection pattern CAP-009 and CHAR-004 used
// ahead of their upstreams. The port shapes mirror the owning tasks'
// documented contracts so integration wiring is a structural match:
//
// - ApprovalGatePort   ← CORE-008 approval state machine (gate 5 "rough cut")
// - RenderAdapter      ← VID-012 rough-cut composition + upstream
//                        remotion/scripts/render-all.mjs (bundle →
//                        selectComposition → renderMedia, scale arg)
// - MediaValidator     ← VID-015 ffprobe wrapper (codec/duration/resolution/
//                        bitrate; integrity pass/fail)
// - ArchivePort        ← GHL durable archive handoff (GHL-00x)
//
// Nothing here shells out, touches the network, or spends money by itself:
// the module is pure orchestration over injected ports, fully testable with
// stubs and a real ffmpeg/ffprobe fixture.

/**
 * The six spec §3 gates by stable id. Gate 5 (rough cut) is the one final
 * render must pass; the full list lives here so error messages name the
 * gate exactly as the spec does.
 */
export const GATES = [
  "concept",
  "script",
  "character",
  "storyboard",
  "rough-cut",
  "canon",
] as const;

export type GateId = (typeof GATES)[number];

/** Approval states a gate can be in (persisted domain state, spec §3). */
export type GateState = "PENDING" | "APPROVED" | "REJECTED";

/** What the approval store (CORE-008) hands the render pipeline. */
export interface GateSnapshot {
  gate: GateId;
  state: GateState;
  /** ISO-8601 instant of the approval, when APPROVED. */
  approvedAt: string | null;
}

/**
 * Port over the durable approval store (CORE-008). The pipeline reads gate
 * state only — it never mutates approvals; approvals advance solely through
 * the CLI/API gate commands (spec §3: explicit operator sign-off).
 */
export type ApprovalGatePort = (gate: GateId) => GateSnapshot;

/** Master output formats (spec §23). Chosen once per series, per-episode override. */
export type MasterFormat = "16:9" | "9:16" | "custom";

/** A resolved render resolution in pixels. */
export interface Resolution {
  width: number;
  height: number;
}

/** Per-episode format override (spec §23: series default, episode override). */
export interface EpisodeFormat {
  seriesFormat: MasterFormat;
  /** Episode override — takes precedence over the series default. */
  override?: MasterFormat;
  /** Required when either format is "custom". */
  custom?: Resolution;
}

/**
 * Declared quality of ONE shot's source media (spec §21: "A 720p generated
 * source upscaled to 1080p is never represented as native 1080p quality").
 * `declared` is what the provider actually produced — provenance from the
 * asset manifest (spec §19), never from the timeline's output resolution.
 */
export interface ShotSourceQuality {
  shotId: string;
  /** Source pixel dimensions as generated by the provider. */
  source: Resolution;
  /** True when the render upscales this shot above its source resolution. */
  upscaled: boolean;
}

/**
 * Quality tiers for rendered output metadata. `native-1080p` is EXCLUSIVE to
 * output whose every source was itself ≥1080p (or scale=1 native 1080p):
 * a 720p source upscaled to a 1080p timeline is `upscaled-720p`, never
 * `native-1080p`. This type is the metadata-flag contract VID-015's probe
 * and the production report read back.
 */
export type QualityTier =
  | "native-1080p"
  | "native-720p"
  | "native-custom"
  | "upscaled-720p"
  | "upscaled-lower"
  | "upscaled-higher"
  | "mixed-source";

/**
 * Per-shot output metadata written into the final's sidecar (09 QC Metadata)
 * and the production report. `qualityTier` for an upscaled shot NEVER claims
 * native (the invariant `upscale.ts` enforces and the tests prove).
 */
export interface ShotQualityRecord {
  shotId: string;
  source: Resolution;
  renderedAt: Resolution;
  upscaled: boolean;
  qualityTier: QualityTier;
}

/** Input shot record the pipeline needs per episode. */
export interface PlannedShot {
  shotId: string;
  /** Source media resolution from the asset manifest (spec §19). */
  source: Resolution;
  /** Provider/model provenance for the production report (spec §21). */
  provider?: string;
  providerModel?: string;
}

/** Spec §23 output formats: series default + per-episode override. */
export interface FormatSpec {
  series: MasterFormat;
  episode?: MasterFormat;
  /** Required when series or episode format is "custom". */
  custom?: Resolution;
}

/** A rough-cut composition ready for final render (VID-012's output). */
export interface RoughCutComposition {
  /** Episode the composition belongs to. */
  episodeId: string;
  /** Ordered shots with their source qualities (asset manifest values). */
  shots: readonly PlannedShot[];
  /** Composition fps — carried through to the final render. */
  fps: number;
  /** Total composition duration in seconds. */
  durationSeconds: number;
}

/**
 * Everything the final render needs for one episode. The rough cut must be
 * APPROVED at gate 5 before this reaches the pipeline (spec §3.5: "no final
 * render before approval").
 */
export interface FinalRenderSpec {
  seriesId: string;
  episodeId: string;
  /** Episode code for deterministic naming, e.g. "S01E01" (spec §19). */
  episodeCode: string;
  episodeTitle?: string;
  format: FormatSpec;
  composition: RoughCutComposition;
  /** Render mode: timeline resolution (default) or scale=1 native. */
  mode?: RenderMode;
  /** Composition version — bumped on re-render; v01 default. */
  version?: number;
  /** Directory the final file renders into. Default: process cwd. */
  outputDir?: string;
}

/**
 * `timeline` renders at the master resolution (upscaling lower-source shots,
 * flagged in metadata). `native` is ownership.md's `--scale=1`: render at
 * native source resolution — no upscaling, no false quality labels.
 */
export type RenderMode = "timeline" | "native";

/** Deterministic final filename (spec §19: provenance in DB, not the name). */
export function finalFileName(episodeCode: string, version: number): string {
  const v = String(version).padStart(2, "0");
  return `${episodeCode}_final_v${v}.mp4`;
}

/** Sidecar metadata filename (spec §17 `09 QC Metadata/`). */
export function sidecarFileName(episodeCode: string, version: number): string {
  return `${finalFileName(episodeCode, version)}.metadata.json`;
}

/**
 * Safe filename token for an episode code: starts alphanumeric, then only
 * alphanumerics, dots, dashes, underscores (no path separators, no leading
 * dot). `finalFileName` builds real filesystem names from this — an
 * unsanitized episodeCode like "../../evil" would escape the output
 * directory (path traversal), so `planFinalRender` validates against this
 * exact pattern (via {@link isSafeEpisodeCode}) before any name is built.
 */
export const EPISODE_CODE_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

/** True when the episode code is a safe filename token. */
export function isSafeEpisodeCode(episodeCode: string): boolean {
  return EPISODE_CODE_PATTERN.test(episodeCode) && !episodeCode.startsWith(".");
}

/**
 * Sanitize a human-typed episode title into a safe single folder-segment
 * leaf: path separators become "-", ALL control characters (C0, DEL, C1)
 * are dropped, leading dots/spaces are stripped (no hidden/dot segments),
 * trailing dots/spaces are stripped (Windows-safe), and the result is
 * length-capped with a final trailing strip so a dot can never survive the
 * cap. The result contains no "/" or "\" and never begins or ends with a
 * dot, so joining it into a folder path cannot traverse.
 */
export function sanitizeTitleLeaf(episodeTitle: string): string {
  const cleaned = episodeTitle
    .replace(/[/\\]/g, "-")
    // eslint-disable-next-line no-control-regex
    .replace(/[\x00-\x1f\x7f-\x9f]/g, "")
    .replace(/^[.\s]+/, "")
    .replace(/[.\s]+$/, "")
    .slice(0, 120)
    .replace(/[.\s]+$/, "");
  return cleaned;
}

function episodeFolderLeaf(episodeCode: string, episodeTitle?: string): string {
  if (!episodeTitle) return episodeCode;
  const cleaned = sanitizeTitleLeaf(episodeTitle);
  return cleaned.length > 0 ? `${episodeCode} - ${cleaned}` : episodeCode;
}

/**
 * Local mirror of the GHL `08 Final/` folder (spec §17): the episode folder
 * `S01E01 - <Title>/08 Final/`. Returned as path segments joined with "/" —
 * the storage layer owns OS separators. The title is sanitized
 * ({@link sanitizeTitleLeaf}) so a hostile title cannot traverse.
 */
export function finalFolderSegments(
  episodeCode: string,
  episodeTitle?: string,
): readonly string[] {
  return [episodeFolderLeaf(episodeCode, episodeTitle), "08 Final"];
}

export function sidecarFolderSegments(
  episodeCode: string,
  episodeTitle?: string,
): readonly string[] {
  return [episodeFolderLeaf(episodeCode, episodeTitle), "09 QC Metadata"];
}