/**
 * @mmcs/database — SQLite connection, migration framework, repository
 * contracts (spec §25). Driver is Node's built-in `node:sqlite`; the
 * `SqliteDatabase` seam keeps repositories portable to PostgreSQL later.
 */
export {
  SQLITE_CONNECTION_DEFAULTS,
  connectSqlite,
  type PreparedStatement,
  type SqliteDatabase,
  type SqliteConnectOptions,
  type SqlOutputValue,
  type SqlValue,
} from "./connection/index.js";

export {
  MIGRATIONS,
  MIGRATIONS_TABLE,
  CREATE_MIGRATIONS_TABLE_SQL,
  MigrationError,
  appliedMigrationIds,
  baselineMigrations,
  jobsAssetsMigrations,
  migrate,
  scenesMigrations,
  sortMigrations,
  type MigrateOptions,
  type MigrateResult,
  type Migration,
  type MigrationRecord,
} from "./migrations/index.js";

export {
  APPROVAL_STATUSES,
  BaseRepository,
  GENERATION_STATUSES,
  KEYFRAME_STRATEGIES,
  PLANNING_STATUSES,
  QC_STATUSES,
  REFERENCE_KINDS,
  REFERENCE_SCORE_AXES,
  SHOT_SPEC_FIELDS,
  SceneRepository,
  ShotReferenceRepository,
  ShotRepository,
  VISUAL_SOURCE_TYPES,
  type ApprovalStatus,
  type CrudRepository,
  type GenerationStatus,
  type KeyframeStrategy,
  type PlanningStatus,
  type QcStatus,
  type ReferenceKind,
  type ReferenceScores,
  type Repository,
  type RowMapper,
  type Scene,
  type SceneInput,
  type ScenePatch,
  type Shot,
  type ShotInput,
  type ShotPatch,
  type ShotReference,
  type ShotReferenceInput,
  type ShotReferencePatch,
  type VisualSourceType,
} from "./repositories/index.js";

export {
  AppearanceVersionRepository,
  ASSET_APPROVAL_STATES,
  ASSET_MANIFEST_FIELDS,
  ARCHIVAL_STATUSES,
  AssetRepository,
  CHARACTER_STATES,
  CharacterRepository,
  CharacterRepositoryError,
  IdentityAssetRepository,
  IdentityVersionRepository,
  JOB_SAFETY_FIELDS,
  JOB_STATES,
  JOB_STATE_ORDER,
  JobStateTransitionError,
  LOCATION_ANGLE_KINDS,
  LOCATION_TIMES_OF_DAY,
  LocationRepository,
  LocationRepositoryError,
  PropRepository,
  ProviderJobRepository,
  SqliteProjectRepository,
  SqliteSeriesRepository,
  SqliteEpisodeRepository,
  formatEpisodeCode,
  isLegalJobTransition,
  type AppearanceVersion,
  type AppearanceVersionInput,
  type ArchivalStatus,
  type AssetApprovalState,
  type AssetManifest,
  type AssetManifestField,
  type AssetPatch,
  type Character,
  type CharacterInput,
  type CharacterPatch,
  type CharacterState,
  type CreateEpisodeInput,
  type CreateProjectInput,
  type CreateSeriesInput,
  type Episode,
  type EpisodeRepository,
  type EpisodeStatus,
  type IdentityAsset,
  type IdentityAssetInput,
  type IdentityAssetPatch,
  type IdentityVersion,
  type IdentityVersionInput,
  type Location,
  type LocationAngleKind,
  type LocationAsset,
  type LocationAssetInput,
  type LocationAssetPatch,
  type LocationInput,
  type LocationPatch,
  type LocationTimeOfDay,
  type Project,
  type ProjectKind,
  type ProjectRepository,
  type ProjectStatus,
  type Prop,
  type PropAsset,
  type PropAssetInput,
  type PropAssetPatch,
  type PropInput,
  type PropPatch,
  type ProviderJob,
  type ProviderJobInput,
  type ProviderJobPatch,
  type ProviderJobState,
  type Series,
  type SeriesRepository,
  type UpdateEpisodePatch,
  type UpdateProjectPatch,
  type UpdateSeriesPatch,
} from "./repositories/index.js";

export {
  isValidAspectRatio,
  ValidationError as SchemaValidationError,
  projectSchemaMigrations,
} from "./repositories/projects/index.js";