/**
 * KIE-008 — temporary provider URL persistence types.
 *
 * Kie result URLs are temporary (runbook §21 / §14.4, spec §36): the only
 * durable copy must be created by archiving them into GHL before they expire.
 * The moment a poll maps to GENERATED_TEMPORARY, every result URL is persisted
 * WITH its expiration (when the provider states one) and the archival handoff
 * (GHL-012) is triggered. Nothing here ever regenerates an asset — losing a
 * URL is archived-error territory, silently resubmitting is forbidden.
 */

import type { KiePipelineState } from "../task/types.js";

/**
 * Handoff status of one temporary URL toward the GHL emergency archival
 * layer (GHL-012 owns the actual GHL work; this module only triggers it).
 */
export type TempUrlHandoffStatus =
  | "PENDING"
  | "TRIGGERED"
  | "FAILED";

/**
 * Durable record for one temporary provider URL. One Kie task result can
 * yield several URLs; each is captured as its own record.
 */
export interface TempUrlRecord {
  /** Unique key: `${ref}:${url}` — idempotent re-capture never duplicates. */
  key: string;
  /** Business reference of the source job (e.g. "shot-42:keyframe-a"). */
  ref: string;
  /** The temporary provider URL itself. */
  url: string;
  /**
   * Provider-stated expiration (ISO-8601), when the provider returns one.
   * Kie's schema states NO TTL for result URLs (verified 2026-08-28 against
   * docs.kie.ai quickstart/seedance/wan schemas) → undefined means "provider
   * TTL unknown", which is treated as not-expired-but-archive-immediately.
   * Never invented (runbook §26.3/§26.4 UNKNOWN policy).
   */
  expiresAt?: string;
  /** Provider model the URL was generated by. */
  providerModel?: string;
  /** Provider task ID (job idempotency key). */
  providerTaskId?: string;
  /** Pipeline state the capture was triggered from. Always GENERATED_TEMPORARY. */
  state: Extract<KiePipelineState, "GENERATED_TEMPORARY">;
  /** When this module first captured the URL, ISO-8601. */
  capturedAt: string;
  /** When the archival handoff was triggered, ISO-8601. */
  handoffTriggeredAt?: string;
  /** Last handoff attempt or failure, ISO-8601. */
  handoffErrorAt?: string;
  /** Why the handoff failed (redacted; never contains credentials). */
  handoffError?: string;
  /** Truncated archive status. */
  handoffStatus: TempUrlHandoffStatus;
}

/** Durable store port for temporary URL records (SQLite impl = CORE-007 layer). */
export interface TempUrlStore {
  load(key: string): Promise<TempUrlRecord | undefined>;
  save(record: TempUrlRecord): Promise<void>;
}

/**
 * Proposed archive request handed to the GHL emergency archival layer
 * (GHL-012). GHL-012 owns validating reachability, ingesting via
 * hosted/binary flow, and marking ARCHIVED — it never regenerates.
 */
export interface TempUrlArchiveRequest {
  /** Business ref carried from the source job. */
  ref: string;
  /** Temporary provider URL to archive NOW. */
  url: string;
  /** Provider-stated expiration when known; undefined = unknown (UNKNOWN policy). */
  expiresAt?: string;
  /** Provider model label, for naming/provenance. */
  providerModel?: string;
  /** Provider task ID, for provenance. */
  providerTaskId?: string;
  /** Capture timestamp, for provenance/audit ordering. */
  capturedAt: string;
}

/** Outcome of one archival handoff attempt. */
export interface TempUrlHandoffResult {
  /** The URL the attempt was for. */
  url: string;
  /** True when the request was handed off (accepted for archival). */
  accepted: boolean;
  /** Redacted failure message; present only when accepted=false. */
  error?: string;
}

/**
 * Port implemented by the GHL-012 emergency archival layer. KIE-008 depends
 * only on this shape, never on @mmcs/media-storage directly (GHL-012 owns
 * that package's emergency-archival directory).
 */
export interface TempUrlArchivalHandoff {
  /** Queue/trigger archival of one temporary URL. Resolves with the outcome. */
  archive(request: TempUrlArchiveRequest): Promise<TempUrlHandoffResult>;
}

/** Options for {@link TempUrlCapturer}. */
export interface TempUrlCapturerOptions {
  /** Injectable clock (ISO string); defaults to Date.now-based. */
  now?: () => string;
}
