// AUTO-GENERATED by scripts/gen-episodic-registry.mjs — do not edit.
import type { EpisodeCompositionConfig } from './types';

export const episodeCompositions: EpisodeCompositionConfig[] = [
  {
    "compositionId": "S01E01",
    "episodeCode": "S01E01",
    "seriesId": "ser_example",
    "episodeId": "ep_example_101",
    "seasonNumber": 1,
    "episodeNumber": 1,
    "fps": 30,
    "width": 1920,
    "height": 1080,
    "durationInFrames": 390,
    "scenes": [
      {
        "sceneId": "sc_101_01",
        "sequenceIndex": 1,
        "sequenceFrom": 0,
        "durationInFrames": 210,
        "shots": [
          {
            "shotId": "sh_101_0101",
            "sequenceIndex": 1,
            "sequenceFrom": 0,
            "durationInFrames": 120,
            "targetDurationSeconds": 4
          },
          {
            "shotId": "sh_101_0102",
            "sequenceIndex": 2,
            "sequenceFrom": 120,
            "durationInFrames": 90,
            "targetDurationSeconds": 3
          }
        ]
      },
      {
        "sceneId": "sc_101_02",
        "sequenceIndex": 2,
        "sequenceFrom": 210,
        "durationInFrames": 180,
        "shots": [
          {
            "shotId": "sh_101_0201",
            "sequenceIndex": 1,
            "sequenceFrom": 210,
            "durationInFrames": 180,
            "targetDurationSeconds": 6
          }
        ]
      }
    ]
  }
];
